---
- name: Restart rsyslogd
  service:
    name: '{{ rsyslog_service }}'
    state: reloaded
    enabled: yes
  become: yes

- name: Restart osqueryd
  service:
    name: osqueryd
    state: restarted
    enabled: yes
  become: yes
